LEARNING_RATE_1: 0.01
LEARNING_RATE_2: 0.01
LEARNING_RATE_3: 0.01
LEARNING_RATE_4: 0.01
LEARNING_RATE_5: 0.01
CLASSES: 2
EPOCHS_1: 30
EPOCHS_2: 30
EPOCHS_3: 30
EPOCHS_4: 30
EPOCHS_5: 30
BATCH_SIZE_1: 80
BATCH_SIZE_2: 80
