artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_source_URL: https://drive.google.com/file/d/15stuLDZkXNOgBUC1rnx5yXYdVPViUjNB/view?usp=sharing
  test_source_URL: https://drive.google.com/file/d/1mjmYzMdnn_UwSEgTQ7i-cJ5WSOokt9Er/view?usp=sharing
  train_data_file: artifacts/data_ingestion/traindata.zip
  test_data_file: artifacts/data_ingestion/testdata.zip
  unzip_dir: artifacts/data_ingestion

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

model_evaluation:
  mlflow_tracking_uri: https://dagshub.com/muzuvajoshua/SwahiliNewsClassifier.mlflow
  mlflow_tracking_username: muzuvajoshua
  mlflow_tracking_password: d96c53ff959b830daebf5fbb90c32cd5f669cce0
